name: Build Application Server

on:
  push:
    paths-ignore:
      - "client/**"
  pull_request:
    paths-ignore:
      - "client/**"

jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          cd server
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        env:
          GOOGLE_RESUME_FOLDER_ID: ${{ secrets.GOOGLE_RESUME_FOLDER_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION_SECRETS_MANAGER }}
          GOOGLE_DOCS_API_KEY_SECRET_NAME: ${{ secrets.GOOGLE_DOCS_API_KEY_SECRET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_SECRETS_MANAGER }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_SECRETS_MANAGER }}
        run: |
          cd server
          pytest
