name: Build Application

on:
  push:
    branches-ignore:
      - "main"
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        node: [16.x, 18.x]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci --prefix client

      - name: Run tests
        run: npm run test:ci --prefix client

      - name: Run TypeScript type check
        run: npm run type-check --prefix client

      - name: Run linter
        run: npm run lint:ci --prefix client

      - name: Build project
        run: npm run build --prefix client
